### ISSUE TITLE
Change notification doesn't work on Outlook for Mac OS

### ISSUE THREAD

**Issue by nguyentoantuit** [microsoftgraph/msgraph-training-changenotifications#16]
I follow this repository to implement the changes notifying on sent mailbox. So whenever user send a message, I would like receive a notification. Everything work fine if I test it on outlook for Windows machine or on outlook web app (both windows and mac), however it doesn't work if I test it on Mac OS. Do you have any idea why it could happen?

My testing environment:
Mac OS version: macOS Sierra version 10.12.6 
Outlook version: Outlook for Mac, version 16.29 (19090802)

**Comment by jasonjoh** [comment]
No sorry. The sample uses ngrok to create a tunnel so that your development machine can receive the notification. I've never tried ngrok on a Mac, but they do have installers for it on their website, so it should work.

I would verify that the ngrok URL on your Mac matches the notification URL in your subscription.
