### ISSUE TITLE
delete resource type does not work

### ISSUE THREAD

**Issue by aarushi-mittal** [microsoftgraph/msgraph-training-changenotifications#25]
Hello Team,

I have been successful in creating the **created and updated** change types for my events resource type following the tutorials.

However **deleted** change type does not trigger any notification.

Kindly assist what I may be missing.

Regards,
Aarushi

**Comment by jasonjoh** [comment]
@andrewconnell does this training use the `deleted` change type? AFAIK it notifies on users and doesn't specify that change type in its subscriptions. Users should support the `deleted` notifications, per https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0.

**Comment by andrewconnell** [comment]
Nope... the module only has the user setup the `updated` event:
https://github.com/microsoftgraph/msgraph-training-changenotifications/blob/master/demos/03-track-changes/Controllers/NotificationsController.cs#L39

FWIW, this has been very hard to test the last few months as the module has the user update the mobile phone or office location of a user and we've seen the notification take in excess of 30m to get sent from graph.

**Comment by jasonjoh** [comment]
@baywet - any ideas?

**Comment by baywet** [comment]
If we're talking about directory entities (user, group, ...), one thing that often trips people is the soft deletion. Resources are soft deleted most of the times (UI, API, etc...) which triggers an **updated** notification. After 30 or 60 days (depending on resources and policies), the resource gets "hard-deleted" which triggers the **deleted** notification.

Regarding the delays, recent global events have translated in bad capacity crunch over the last few months (since Feb/March until a few weeks ago) resulting in added latency in change notifications delivery (up to a few hours...).
The team has been working hard at addressing the bottlenecks and weaknesses that have been revealed by the situations.
The last major changes have roll-out 2 weeks ago and you should have seen an improvement in latency and reliability.

I'm happy to connect offline with you @andrewconnell if you have recent numbers (and traces) that say otherwise :)

**Comment by andrewconnell** [comment]
Last experience we saw this was in June when we refreshed this module's content. Didn't doc any numbers... when we refresh it again this quarter we'll let you know if we see excessive delays. What's the SLA on the expected time to receive a notification from the event happening?

**Comment by baywet** [comment]
thanks! Working on it...
https://github.com/microsoftgraph/microsoft-graph-docs/pull/9235

**Comment by jasonjoh** [comment]
Awesome thanks guys. @aarushi-mittal I believe @baywet has answered your question about `deleted` with the user resource, so I'm closing this.
