### ISSUE TITLE
Subscription constantly dying out

### ISSUE THREAD

**Issue by aarushi-mittal** [microsoftgraph/msgraph-training-changenotifications#26]
Hello Team,

I am using Ms graph notifications mechanism for managing subscriptions on a events resource.
I am handling renewing of subscriptions every 2 minutes.
However the subscriptions die put abruptly.
I handled it using a logic to create a new subscription in case the code memory has no subscription however that also did not work when I looked at the subscriptions today morning.

The last updated one is on Friday.
Saturday and Sunday have no logs for renewal.
Kindly help me out in case I am missing an important factor as this is a part of a client project

**Comment by jasonjoh** [comment]
@aarushi-mittal we're not setup to provide general support in GitHub issues, so I'm going to close this. However: I'd say that renewing every 2 minutes is excessive. When you create the subscription, you set an expiration date/time on it, which has a maximum of 3 days from the point of creation. You should fairly comfortably be able to only renew the subscription once a day, assuming you set the expiration to the max.

**Comment by SteveRogers-Enghouse** [comment]
> Hello Team,
> 
> I am using Ms graph notifications mechanism for managing subscriptions on a events resource.
> I am handling renewing of subscriptions every 2 minutes.
> However the subscriptions die put abruptly.
> I handled it using a logic to create a new subscription in case the code memory has no subscription however that also did not work when I looked at the subscriptions today morning.
> 
> The last updated one is on Friday.
> Saturday and Sunday have no logs for renewal.
> Kindly help me out in case I am missing an important factor as this is a part of a client project

Hi friend,

I don't know if your problem was resolved.

The subscription model often depends upon what you are asking for.
- and if your notification endpoint remains available
- when you get a notification, you need to respond with a 200 0K in time
- otherwise MS Graph may kill your subscription

So, subscribe to Presence Notifications under BETA MSGRaph API
- you may need to renew it a lot more often than if you subscribed to call records - in this case you can only have a single subscription that can only last an hour (as at 04 Feb 2021)
- a notification from Presence could get to you anywhere between 0-60 seconds of the event, or not at all
- you would only know when you received the notification (not when the state was changed)
-- when the actual user changed their status - who knows?
- latency for call records or other notifications is potentially a lot longer
-- so trying to make sense of information that you get can be difficult

In the past, I have found that polling gets you the information a long time before you would get a notification sent to you
- poll for user details every minute
-  the user info is changed way before you get a notification if you subscribe to user's being changed

Sometimes, you need to look at their latency for subscription / notification models
- A polling mechanism might get you what you need sooner and in a more controlled fashion
- - consider polling if it is available if you are writing a reporting solution.  And don't want to miss anything.
-- Lots to think about
- it also often depends on what you want to do with the information when you get it
-- and what your assumptions are that you make when you receive them
--- if you look at MS Docs, there is not enough information to compare Polling vs Notifications
---- so if you base your solution on what results you get back
----- that might not be logic that you can trust in the future.
------ rely upon notifications
------- receive the notifications when a user has gone Active, Busy, Idle in an instant
-------- can you rely upon when you receive them to know their last current state?
--------- they might be Idle, and you think that they are Busy, depending on when they arrived (race condition)

**Comment by SteveRogers-Enghouse** [comment]
For subscription / latency for notifications. Check out.
- https://docs.microsoft.com/en-us/graph/webhooks

search for **latency**
