### ISSUE TITLE
Not getting notified when User contact info is changed

### ISSUE THREAD

**Issue by sujithaPalakolanu** [microsoftgraph/msgraph-training-changenotifications#29]
I am able to get the subscription id but when I am updating user contact info am not notified in console
My notification url is hosted in azure

var sub = new Microsoft.Graph.Subscription();
            sub.ChangeType = "created";
            sub.NotificationUrl = "https://AppserviceName.azurewebsites.net/api/notifications";
            sub.Resource = "/users";
            sub.ExpirationDateTime = DateTime.UtcNow.AddMinutes(15);

**Comment by jasonjoh** [comment]
See #17. You can see a lag between making the change and getting notification of around 10 minutes. If you're seeing longer than that, the recommendation is to open a support case.

**Comment by SteveRogers-Enghouse** [comment]
> See #17. You can see a lag between making the change and getting notification of around 10 minutes. If you're seeing longer than that, the recommendation is to open a support case.

It has been a while since I wrote code to use this, but I agree that the notification may not come back promptly.

Check the following link and search for **Latency**
https://docs.microsoft.com/en-us/graph/webhooks

Sorry, I have no time to look at your code or logic.  But, from memory.
- I would make your subscription **ExpirationDateTime** date longer.
-- double check what you are sending in this parameter. MS Graph is expecting a UTC datetime as a string like "2016-03-20T11:00:00.0000000Z" 
- Latency of 10 minutes is a guideline and may be longer depending on what the MS Infrastructure is doing and traffic
-- So your subscription may end before you get a notification
- Your code should have a mechanism to renew the subscription
-- search doc for **Renewing a subscription**
--- maximum expiration times look at https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0
---- search for **Maximum length of subscription per resource type**
- Your subscription code must handle a message coming back from MS Graph and reply with a 200 OK or the subscription will not work
-- otherwise you will not receive a notification
-- When you send your subscription request, MS Graph will send your endpoint a response and requires a 200 OK to be sent back.  Otherwise MS Graph will not think that your endpoint is valid.
--- search the doc for **Notification endpoint validation**

Other things to worry about.
- if your application is not available and MS Graph sends you a notification and cannot reach the endpoint
-- it may remove the subscription
--- Last time I checked that could happen if MS Graph tries to send you a notifications and your endpoint is not accessible for as little as 20 minutes.  That may have changed.  I don't have a link for that, but it was in the documentation when I was looking at subscribing to call notifications using Beta.  It might be different for user changes.

I hope that this helps,

Steve R

**Comment by SteveRogers-Enghouse** [comment]
> > See #17. You can see a lag between making the change and getting notification of around 10 minutes. If you're seeing longer than that, the recommendation is to open a support case.
> 
> It has been a while since I wrote code to use this, but I agree that the notification may not come back promptly.
> 
> Check the following link and search for **Latency**
> https://docs.microsoft.com/en-us/graph/webhooks
> 
> Sorry, I have no time to look at your code or logic. But, from memory.
> 
> * I would make your subscription **ExpirationDateTime** date longer.
>   -- double check what you are sending in this parameter. MS Graph is expecting a UTC datetime as a string like "2016-03-20T11:00:00.0000000Z"
> * Latency of 10 minutes is a guideline and may be longer depending on what the MS Infrastructure is doing and traffic
>   -- So your subscription may end before you get a notification
> * Your code should have a mechanism to renew the subscription
>   -- search doc for **Renewing a subscription**
>   --- maximum expiration times look at https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0
>   ---- search for **Maximum length of subscription per resource type**
> * Your subscription code must handle a message coming back from MS Graph and reply with a 200 OK or the subscription will not work
>   -- otherwise you will not receive a notification
>   -- When you send your subscription request, MS Graph will send your endpoint a response and requires a 200 OK to be sent back.  Otherwise MS Graph will not think that your endpoint is valid.
>   --- search the doc for **Notification endpoint validation**
> 
> Other things to worry about.
> 
> * if your application is not available and MS Graph sends you a notification and cannot reach the endpoint
>   -- it may remove the subscription
>   --- Last time I checked that could happen if MS Graph tries to send you a notifications and your endpoint is not accessible for as little as 20 minutes.  That may have changed.  I don't have a link for that, but it was in the documentation when I was looking at subscribing to call notifications using Beta.  It might be different for user changes.
> 
> I hope that this helps,
> 
> Steve R

I also remember in handling the notification you need to reply with a 202 OK
- I think that if MS Graph doesn't get it it may remove your subscription
-- https://docs.microsoft.com/en-us/graph/webhooks
--- search for **Processing the change notification**

**Comment by SteveRogers-Enghouse** [comment]
> > > See #17. You can see a lag between making the change and getting notification of around 10 minutes. If you're seeing longer than that, the recommendation is to open a support case.
> > 
> > 
> > It has been a while since I wrote code to use this, but I agree that the notification may not come back promptly.
> > Check the following link and search for **Latency**
> > https://docs.microsoft.com/en-us/graph/webhooks
> > Sorry, I have no time to look at your code or logic. But, from memory.
> > 
> > * I would make your subscription **ExpirationDateTime** date longer.
> >   -- double check what you are sending in this parameter. MS Graph is expecting a UTC datetime as a string like "2016-03-20T11:00:00.0000000Z"
> > * Latency of 10 minutes is a guideline and may be longer depending on what the MS Infrastructure is doing and traffic
> >   -- So your subscription may end before you get a notification
> > * Your code should have a mechanism to renew the subscription
> >   -- search doc for **Renewing a subscription**
> >   --- maximum expiration times look at https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0
> >   ---- search for **Maximum length of subscription per resource type**
> > * Your subscription code must handle a message coming back from MS Graph and reply with a 200 OK or the subscription will not work
> >   -- otherwise you will not receive a notification
> >   -- When you send your subscription request, MS Graph will send your endpoint a response and requires a 200 OK to be sent back.  Otherwise MS Graph will not think that your endpoint is valid.
> >   --- search the doc for **Notification endpoint validation**
> > 
> > Other things to worry about.
> > 
> > * if your application is not available and MS Graph sends you a notification and cannot reach the endpoint
> >   -- it may remove the subscription
> >   --- Last time I checked that could happen if MS Graph tries to send you a notifications and your endpoint is not accessible for as little as 20 minutes.  That may have changed.  I don't have a link for that, but it was in the documentation when I was looking at subscribing to call notifications using Beta.  It might be different for user changes.
> > 
> > I hope that this helps,
> > Steve R
> 
> I also remember in handling the notification you need to reply with a 202 OK
> 
> * I think that if MS Graph doesn't get it it may remove your subscription
>   -- https://docs.microsoft.com/en-us/graph/webhooks
>   --- search for **Processing the change notification**

btw - I had a quick look at your code and it seems that you are using a .net library class as a wrapper for subscribing.
- When I wrote my code at a lower level and I used http requests and did not  use the .net MSGraph library
-- I was writing for BETA and there was no library available for me at the time :(

So, it is possible that the library class handles the UTC datetime that you are sending.
- regardless, I think that you will have to reply to the Subscription and Notifications sent to you by MS Graph
