### ISSUE TITLE
Multiple notifications in the same second

### ISSUE THREAD

**Issue by newbiedev123** [microsoftgraph/msgraph-training-changenotifications#39]
Hi,
We are getting multiple notifications at the same second. So before the deltalink changes in the first notification, the second notification comes in. In this situation the same changes are coming back from the delta query.

What is the best way to handle this?

**Comment by jasonjoh** [comment]
You can get multiple notifications rapidly if multiple changes are happening. If you are doing a delta query in response to receiving a notification, it's advisable to not run them in parallel. If you get multiple notifications, then queue the delta queries. Always use the `deltaLink` from the previous query when running a delta query.

**Comment by newbiedev123** [comment]
@jasonjoh , thanks for your reply. 
How do I queue the delta Queries? Do you mean Azure Queue or similar?
If the app restart the deltalink will ne null. In that case will it fetch all the notifications from the start? 
Using a database to store the deltalink seem to be unnecessarily complicated. Is there a better way of storing the deltalink in a real application?

**Comment by jasonjoh** [comment]
How to queue and how to store deltaLink are implementation details that aren't related to Graph. You have to decide what makes sense to you for your scenario.

- "Queue" may be an overly-complicated word :D. You could do something as simple as just ensuring that you don't start a new delta query while one is being processed. If you get a notification in while a delta query is in progress, just set a flag so that you know to do second query when the in-progress one is done.
- Storing deltaLink could be done in a number of ways. Write it to a file, store it in a database, etc.

To answer your question about a blank deltaLink - yes, if you issue a delta query without one you will be essentially re-syncing everything.
